### ISSUE TITLE
Error: hyper-pokemon plugin not working.

### ISSUE THREAD

**Issue by fomenyesu** [klauscfhq/hyper-pokemon#18]
Hi,
I installed hyper1.3.3 in my mac book , and run hpm install hyper-pokemon to install hyper-pokemon plugin.
After installed, it returned error ：

```
Uncaught Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Cannot read property 'toLowerCase' of undefined     remote.js:217
Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Cannot read property 'toLowerCase' of undefined
    at callFunction (/Applications/Hyper.app/Contents/Resources/electron.asar/browser/rpc-server.js:235:11)
    at EventEmitter.<anonymous> (/Applications/Hyper.app/Contents/Resources/electron.asar/browser/rpc-server.js:342:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/Applications/Hyper.app/Contents/Resources/electron.asar/browser/api/web-contents.js:231:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)metaToValue @ remote.js:217L.subscribe @ bundle.js:47emitOne @ events.js:96emit @ events.js:188
```

It's hyper-pokemon plugin no working in hyper1.3.3 ?
Thanks for your work !

**Comment by klaudiosinani** [comment]
Hi @fomenyesu!
You can try installing [`hyper-pokemon` manually](https://github.com/hyper-pokemon/hyper-pokemon#manually-through-hyperjs), using the `plugins` array inside of the `~/.hyper.js` config file. Hopefully that will solve the issue and activate the theme. If not, then please feel free to ping us back any time! Thank you a lot for your kind words : )

**Comment by sdkcarlos** [comment]
I tried with 2 methods, using the CLI to install it and manually by modifying, however i keep getting the following exception in the developer tools:


```
bundle.js:1 Error: Cannot find module 'C:\Users\sdkca\.hyper_plugins\node_modules\hyper-pokemon'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (C:\Users\sdkca\AppData\Local\hyper\app-1.3.3\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at require (internal/module.js:20:19)
    at le.plugins.concat.map.ce (file:///C:/Users/sdkca/AppData/Local/hyper/app-1.3.3/resources/app/dist/bundle.js:1:8876)
    at Array.map (native)
    at se (file:///C:/Users/sdkca/AppData/Local/hyper/app-1.3.3/resources/app/dist/bundle.js:1:8830)
    at Object.<anonymous> (file:///C:/Users/sdkca/AppData/Local/hyper/app-1.3.3/resources/app/dist/bundle.js:1:10365)
    at __webpack_require__ (file:///C:/Users/sdkca/AppData/Local/hyper/app-1.3.3/resources/app/dist/bundle.js:1:119)
    at Object.<anonymous> (file:///C:/Users/sdkca/AppData/Local/hyper/app-1.3.3/resources/app/dist/bundle.js:47:368728)
```

Any idea of what's wrong ? Using Windows 10 and Hyper 1.3.3 ...

**Comment by sdkcarlos** [comment]
Made it work by following the instructions of @beilunyang on the issue https://github.com/hyper-pokemon/hyper-pokemon/issues/7:

Remove the hyper-pokemon plugin of hyper. Then switch to the directory of `.hyper_plugins` (in Windows C:\Users\yourusername\.hyper_plugins):

```batch
cd .hyper_plugins
```

Then install the hyper-pokemon package with NPM:

```batch
npm install hyper-pokemon --save
```

Close all instances of Hyper. Finally, enable the hyper-pokemon package manually in the .hyper file:

```javascript
{
    config: {

        /**/

        pokemon: 'gengar', // Define your favorite pokemon theme
        pokecursor: 'true', // Activate your theme's pokecursor
        pokemonSyntax: 'dark', // Define the color of the terminal tabs
        unibody: 'true', // Define the color of the Hyper window header
        poketab: 'false',

        /**/
    }
    plugins: [
        "hyper-pokemon"
    ],
}
```

And open Hyper again and it should work:


![hyper windows](https://user-images.githubusercontent.com/11634719/29088927-0a391ab2-7c7b-11e7-90f0-94c7305015c2.png)

**Comment by klaudiosinani** [comment]
@sdkcarlos That's so great!
I had a feeling that the issue was related to (#7), hopefully it will be resolved with the upcoming release of Hyper. We will definitely add the fix that @beilunyang and you pointed out, as a heavily credible solution for future issues. Glad you made it work on your end and really hope that you enjoy it! You are more than welcome to share your thoughts about the project any time : )
